version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: king2023
      MYSQL_DATABASE: AAS
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"  # Mapear a porta 3306 do contêiner para a porta 3306 do host (0.0.0.0)
    volumes:
      - D:\AAS-DB:/var/lib/mysql

volumes:
  mysql_data:
